openapi: 3.1.0
info:
  title: Reservations
  version: '1.0'
servers:
  - url: 'https://teched22.azurewebsites.net'
    description: Production
tags:
  - name: Registrations
    description: Správa registrací
paths:
  '/registrations/{id}':
    parameters:
      - schema:
          type: string
          minLength: 6
          maxLength: 6
          example: lakso9
        name: id
        in: path
        required: true
        description: APID (6 chars)
    get:
      summary: Registrace dle ID
      tags:
        - Registrations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
          headers: {}
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '404':
          $ref: '#/components/responses/404-NotFound'
        '500':
          $ref: '#/components/responses/500-InternalServerError'
      operationId: GetRegistration
      description: Return registration based on APID
  /registrations:
    post:
      summary: Create registration
      operationId: CreateRegistration
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '500':
          $ref: '#/components/responses/500-InternalServerError'
      description: Create registration based on name and choosed date.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationCreate'
        description: Registrace k vytvoření
      parameters: []
      tags:
        - Registrations
components:
  schemas:
    Registration:
      title: Registration
      type: object
      examples:
        - id: ksopek8
          name: Miroslav Holec
          date: '2019-08-24T14:15:22Z'
      properties:
        id:
          type: string
          minLength: 6
          maxLength: 6
          description: Identifikátor APID
        name:
          type: string
          maxLength: 30
          description: Jméno účastníka
          example: Jan Novák
        date:
          type: string
          format: date-time
          description: Datum
    RegistrationCreate:
      title: RegistrationCreate
      type: object
      description: Model pro registraci na událost. Registruje se účastník vůči vybranému datu.
      properties:
        name:
          type: string
          maxLength: 30
          description: Jméno účastníka akce
          example: Jan Novák
        date:
          type: string
          format: date-time
          description: Datum na které se registruje
      required:
        - name
        - date
      examples:
        - name: Jan Novák
          date: '2019-08-24T14:15:22Z'
    ProblemDetails:
      title: ProblemDetails
      type: object
      description: Chyba vzniklá v REST API
      properties:
        title:
          type: string
          description: Druh chyby
          example: Internal server error
        type:
          type: string
          format: uri
          description: 'Typ chyby, informace o chybě'
          example: 'https://www.restapi.cz/probs/problem-details'
        status:
          type: integer
          description: HTTP Status Code
          maximum: 599
          minimum: 400
          example: 500
        detail:
          type: string
          description: Detailní informace
      examples:
        - title: Internal server error
          type: 'https://www.restapi.cz/probs/problem-details'
          status: 500
          detail: '---'
    ValidationProblemDetails:
      title: ValidationProblemDetails
      type: object
      description: Chyba vzniklá v REST API
      examples:
        - title: Validation failed!
          type: 'https://www.restapi.cz/probs/problem-details'
          status: 400
          detail: See more in errors array
          errors:
            - propertyName: Name
              errorMessage: Name is required!
              attemptedValue: null
              errorCode: NotEmptyValidator
      properties:
        title:
          type: string
          description: Druh chyby
          example: Internal server error
        type:
          type: string
          format: uri
          description: 'Typ chyby, informace o chybě'
          example: 'https://www.restapi.cz/probs/problem-details'
        status:
          type: integer
          description: HTTP Status Code
          maximum: 599
          minimum: 400
          example: 500
        detail:
          type: string
          description: Detailní informace
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      type: object
      properties:
        propertyName:
          type: string
          example: Name
        errorMessage:
          type: string
          example: Name is required!
        attemptedValue:
          type: string
        errorCode:
          type: string
          example: NotEmptyValidator
      examples:
        - propertyName: Name
          errorMessage: Name is required!
          attemptedValue: null
          errorCode: NotEmptyValidator
      description: Validační chyba
  responses:
    400-BadRequest:
      description: Validation failed response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationProblemDetails'
          examples:
            Default example:
              value:
                title: Validation failed!
                type: 'https://www.restapi.cz/probs/problem-details'
                status: 400
                detail: See more in errors array
                errors:
                  - propertyName: Name
                    errorMessage: Name is required!
                    attemptedValue: null
                    errorCode: NotEmptyValidator
      headers:
        RequestId:
          schema:
            type: string
            example: f65eee54-bfe9-4113-a715-8cbb5ddcd36f
          description: Request ID for logging and tracing
    500-InternalServerError:
      description: Internal Server Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            Default 500 error:
              value:
                title: Internal server error
                type: 'https://www.restapi.cz/probs/problem-details'
                status: 500
      headers:
        RequestId:
          schema:
            type: string
            example: f65eee54-bfe9-4113-a715-8cbb5ddcd36f
          description: Request ID for logging and tracing
    404-NotFound:
      description: Object not found response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            Default not found:
              value:
                title: Object not found!
                type: 'https://www.restapi.cz/probs/problem-details'
                status: 404
      headers:
        RequestId:
          schema:
            type: string
            example: f65eee54-bfe9-4113-a715-8cbb5ddcd36f
          description: Request ID for logging and tracing
